paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    url: camfasco.ca
    disable_url: false
    preview:
      text:
        - text: welcome
      subtext:
      icon:
      icon_color:
      icon_background_color:
      image:
      metadata:
      gallery:
    _editables:
      text:
        allow_custom_markup: true
        remove_custom_markup: false
        bold: true
        copyformatting: true
        italic: true
        link: true
        paths:
          uploads:
          uploads_filename:
          uploads_use_relative_path:
          static:
          dam_uploads:
          dam_uploads_filename:
          dam_static:
        redo: true
        removeformat: true
        strike: true
        subscript: true
        superscript: true
        underline: true
        undo: true
      image:
        expandable: true
        height: 3
        image_size_attributes: true
        mime_type: image/jpeg
        paths:
        resize_style: contain
        width: 3
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  account:
    path: src/pages/account
    icon: ac_unit
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
editor:
  default_path: camfasco.ca
timezone: America/Toronto
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
